project:
  type: website

website:
  title: "**PRABU JEYABALAN**"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: certifications.qmd
        text: Certifications

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



