project:
  type: website

website:
  title: "**PRABU JEYABALAN**"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: certifications.qmd
        text: Certifications



format:
  html:
    css: styles.css
    toc: false
    page-layout: full
    html-math-method: mathjax  # (Optional, but ensures full HTML support)




