---
title: "About"
format:
  html:
    css: styles.css
---

<div class="about-container">


I am an avid explorer who enjoys hiking, long-distance biking across the country, and playing volleyball. When I’m not analyzing data, I love spending time with my 7-year-old Rottweiler, Caesar. My passion for problem-solving and curiosity extend beyond adventure and into my work as a data analyst and business intelligence professional.

With over five years of experience in market research, predictive analytics, and data-driven decision-making, I am currently pursuing an M.S. in Applied Business Analytics at Boston University. My focus is on cloud-based analytics solutions and big data tools that optimize business strategies.

I specialize in Python, R, SQL, Tableau, Power BI, and AWS, using these tools to develop predictive models, automate data pipelines, and generate actionable insights that drive business growth. Previously, as the founder of Cradle Logistics, I leveraged data-driven strategies to enhance supply chain efficiency and increase profitability by 20%.

Passionate about AI-driven analytics and business intelligence, I strive to bridge the gap between data and strategic decision-making. Whether it’s solving complex business challenges or embarking on my next adventure, I am always looking for new opportunities to explore and grow.

</div>










